# Generated by Django 3.1.4 on 2020-12-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Description', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('videofile', models.FileField(null=True, upload_to='videos/%Y/%m/%d/', verbose_name='')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
