# Generated by Django 3.1.4 on 2021-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snap',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='snap',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
