# Generated by Django 4.0 on 2022-01-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_snap_http_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='lession',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
